### ISSUE TITLE
APIDIR not found

### ISSUE THREAD

**Issue by johnny-mac** [simple64/simple64-audio-sdl2#4]
Hi, I know this is a noobish question and I'm sorry to bother you, but where is the APIDIR for mupen64plus & how would I input the location into a make command or something of that sort? 
I'm trying to package this for Void Linux MUSL, I've got this package built & uploaded to the AUR already without issue. I really appreciate the work you do so that I can play games with better video & audio / better front-ends.

**Comment by johnny-mac** [comment]
Even when trying to build it out of container, it gives me an error about the APIDIR.... I've tried googling this up, but haven't found any real results. Your input is greatly appreciated, thank you for your time.

**Comment by loganmc10** [comment]
You need to put mupen64plus-core in the same directory as mupen64plus-audio-sdl2, or point APIDIR to the location of mupen64plus-core/src/api

**Comment by johnny-mac** [comment]
...how do I point the APIDIR though? just like... export APIDIR= ? 
And where do I find mupen64plus-core/src/api ??? The source-code of mupen? :/ 
I've never had to do this before....

**Comment by johnny-mac** [comment]
```
make: Entering directory '/home/user/Compiles/mupen64plus-audio-sdl2/projects/unix'
    CC  _obj/main.o
../../src/main.c:34:10: fatal error: m64p_common.h: No such file or directory
 #include "m64p_common.h"
          ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:298: _obj/main.o] Error 1
make: Leaving directory '/home/user/Compiles/mupen64plus-audio-sdl2/projects/unix'
```
